### ISSUE TITLE
Godeye

### ISSUE THREAD

**Issue by ghost** [kkent030315/evil-mhyprot-cli#6]
Hi Kento,

I just figured out that your blog closed, is there any chance that you could send me your articles so I can read them again? I'd really appreciate it, thank you!

**Comment by icebarf** [comment]
Hello! Here is the archives version of the article. 

https://web.archive.org/web/20211204031301/https://www.godeye.club/2021/05/20/001-disclosure-mhyprot.html

**Comment by ghost** [comment]
thank you!

**Comment by icebarf** [comment]
please close the issus if its resolved
